<?php

declare(strict_types=1);

namespace MonkeysLegion\Mlc\Tests\Cache;

use MonkeysLegion\Mlc\Cache\CompiledPhpCache;
use MonkeysLegion\Mlc\Config;
use MonkeysLegion\Mlc\Exception\FrozenConfigException;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\TestCase;

#[CoversClass(CompiledPhpCache::class)]
#[CoversClass(Config::class)]
final class CompiledPhpCacheTest extends TestCase
{
    private string $cacheDir;
    private CompiledPhpCache $cache;

    protected function setUp(): void
    {
        $this->cacheDir = __DIR__ . '/../../.cache_test';
        if (!is_dir($this->cacheDir)) {
            mkdir($this->cacheDir, 0775, true);
        }
        $this->cache = new CompiledPhpCache($this->cacheDir);
    }

    protected function tearDown(): void
    {
        $this->cache->clear();
        if (is_dir($this->cacheDir)) {
            rmdir($this->cacheDir);
        }
    }

    // =========================================================================
    // CompiledPhpCache — PSR-16 contract
    // =========================================================================

    #[Group('cache')]
    public function testSetAndGet(): void
    {
        $this->assertTrue($this->cache->set('foo', 'bar'));
        $this->assertSame('bar', $this->cache->get('foo'));
    }

    #[Group('cache')]
    public function testGetNonExistentReturnsDefault(): void
    {
        $this->assertNull($this->cache->get('nothing'));
        $this->assertSame('default', $this->cache->get('nothing', 'default'));
    }

    #[Group('cache')]
    public function testHas(): void
    {
        $this->assertFalse($this->cache->has('foo'));
        $this->cache->set('foo', 'bar');
        $this->assertTrue($this->cache->has('foo'));
    }

    #[Group('cache')]
    public function testDelete(): void
    {
        $this->cache->set('foo', 'bar');
        $this->assertTrue($this->cache->delete('foo'));
        $this->assertNull($this->cache->get('foo'));
        $this->assertFalse($this->cache->has('foo'));
    }

    #[Group('cache')]
    public function testDeleteNonExistentReturnsTrue(): void
    {
        // PSR-16: delete() MUST return true even if the key did not exist
        $this->assertTrue($this->cache->delete('ghost'));
    }

    #[Group('cache')]
    public function testClear(): void
    {
        $this->cache->set('a', 1);
        $this->cache->set('b', 2);
        $this->assertTrue($this->cache->clear());
        $this->assertNull($this->cache->get('a'));
        $this->assertNull($this->cache->get('b'));
    }

    // =========================================================================
    // CompiledPhpCache — immutability / OPcache contract
    // =========================================================================

    #[Group('cache')]
    public function testTtlIsIgnoredCacheIsImmutable(): void
    {
        // TTL must be silently ignored — CompiledPhpCache is immutable by design.
        $this->cache->set('key', 'value', 1);   // ttl=1s — ignored
        $this->assertSame('value', $this->cache->get('key'));
        $this->assertTrue($this->cache->has('key'));
    }

    #[Group('cache')]
    public function testCompiledFileIsValidPhp(): void
    {
        $data = ['database' => ['host' => 'localhost', 'port' => 3306]];
        $this->cache->set('config', $data);

        $safe = preg_replace('/[^A-Za-z0-9_.\-]/', '_', 'config');
        $path = $this->cacheDir . DIRECTORY_SEPARATOR . $safe . '.generated.php';

        $this->assertFileExists($path);
        $contents = file_get_contents($path);
        $this->assertStringStartsWith('<?php', $contents);
        $this->assertStringContainsString('return ', $contents);
        $this->assertStringContainsString('Generated by MonkeysLegion CompiledPhpCache', $contents);
    }

    #[Group('cache')]
    public function testCompiledFileIsReloadedAsArray(): void
    {
        $data = ['key' => 'value', 'nested' => ['a' => true, 'b' => 42]];
        $this->cache->set('reload_test', $data);

        $freshCache = new CompiledPhpCache($this->cacheDir);
        $this->assertSame($data, $freshCache->get('reload_test'));
    }

    #[Group('cache')]
    public function testSetOverwritesExistingKey(): void
    {
        $this->cache->set('key', 'first');
        $this->cache->set('key', 'second');
        $this->assertSame('second', $this->cache->get('key'));
    }

    #[Group('cache')]
    public function testComplexNestedData(): void
    {
        $data = [
            'nested' => ['a' => 1, 'b' => true, 'c' => null],
            'list'   => [1, 2, 3],
            'string' => "Hello\nWorld",
            'float'  => 3.14,
        ];

        $this->cache->set('complex', $data);
        $this->assertSame($data, $this->cache->get('complex'));
    }

    // =========================================================================
    // CompiledPhpCache — PSR-16 multiple helpers
    // =========================================================================

    #[Group('cache')]
    public function testGetMultiple(): void
    {
        $this->cache->set('x', 10);
        $this->cache->set('y', 20);

        $result = iterator_to_array($this->cache->getMultiple(['x', 'y', 'z'], 'missing'));

        $this->assertSame(10, $result['x']);
        $this->assertSame(20, $result['y']);
        $this->assertSame('missing', $result['z']);
    }

    #[Group('cache')]
    public function testSetMultiple(): void
    {
        $this->assertTrue($this->cache->setMultiple(['p' => 'ping', 'q' => 'pong']));
        $this->assertSame('ping', $this->cache->get('p'));
        $this->assertSame('pong', $this->cache->get('q'));
    }

    #[Group('cache')]
    public function testDeleteMultiple(): void
    {
        $this->cache->set('m', 1);
        $this->cache->set('n', 2);
        $this->assertTrue($this->cache->deleteMultiple(['m', 'n']));
        $this->assertFalse($this->cache->has('m'));
        $this->assertFalse($this->cache->has('n'));
    }

    // =========================================================================
    // Config — default state: no locks, dual-layer dormant
    // =========================================================================

    #[Group('dual-layer')]
    public function testFreshConfigHasNothingLocked(): void
    {
        $config = new Config(['key' => 'val']);

        $this->assertFalse($config->isLocked());
        $this->assertFalse($config->areOverridesLocked());
        $this->assertFalse($config->isDualLayerActive());
    }

    #[Group('dual-layer')]
    public function testGetReadsBypassesOverrideLayerWhenDormant(): void
    {
        $config = new Config(['db' => ['host' => 'localhost']]);

        // Dual-layer is dormant — direct path, no override-layer overhead
        $this->assertFalse($config->isDualLayerActive());
        $this->assertSame('localhost', $config->get('db.host'));
    }

    // =========================================================================
    // Config — dual-layer auto-activation
    // =========================================================================

    #[Group('dual-layer')]
    public function testFirstOverrideActivatesDualLayer(): void
    {
        $config = new Config(['x' => 1]);
        $this->assertFalse($config->isDualLayerActive());

        $config->override('x', 2);

        $this->assertTrue($config->isDualLayerActive());
        $this->assertSame(2, $config->get('x'));
    }

    #[Group('dual-layer')]
    public function testOverrideShadowsBaseValue(): void
    {
        $config = new Config(['db' => ['host' => 'localhost', 'port' => 3306]]);
        $config->override('db.host', '10.0.0.1');

        $this->assertSame('10.0.0.1', $config->get('db.host'));
        // Base layer for sibling key untouched
        $this->assertSame(3306, $config->get('db.port'));
    }

    #[Group('dual-layer')]
    public function testOverrideAddsNewKey(): void
    {
        $config = new Config(['existing' => 'yes']);
        $config->override('brand_new', 'runtime_value');

        $this->assertSame('runtime_value', $config->get('brand_new'));
        $this->assertNull($config->get('non_existing'));
    }

    #[Group('dual-layer')]
    public function testBaseLayerIsNeverMutated(): void
    {
        $config = new Config(['env' => 'production']);
        $config->override('env', 'testing');

        // all() returns the compiled base — override must NOT appear there
        $this->assertSame('production', $config->all()['env']);

        // get() applies override priority
        $this->assertSame('testing', $config->get('env'));
    }

    #[Group('dual-layer')]
    public function testMultipleOverridesAccumulate(): void
    {
        $config = new Config(['a' => 1, 'b' => 2, 'c' => 3]);
        $config->override('a', 10);
        $config->override('b', 20);

        $this->assertSame(10, $config->get('a'));
        $this->assertSame(20, $config->get('b'));
        $this->assertSame(3,  $config->get('c')); // untouched
    }

    #[Group('dual-layer')]
    public function testGetOverridesReturnsMap(): void
    {
        $config = new Config(['x' => 1]);
        $config->override('x', 99);
        $config->override('y', 'new');

        $overrides = $config->getOverrides();
        $this->assertSame(['x' => 99, 'y' => 'new'], $overrides);
    }

    // =========================================================================
    // Config — lock() : Lock 1 (sealed, no overrides allowed at all)
    // =========================================================================

    #[Group('dual-layer')]
    public function testLockSetsFlag(): void
    {
        $config = new Config(['x' => 1]);
        $this->assertFalse($config->isLocked());
        $config->lock();
        $this->assertTrue($config->isLocked());
    }

    #[Group('dual-layer')]
    public function testLockBlocksOverride(): void
    {
        $config = new Config(['key' => 'val']);
        $config->lock();

        $this->expectException(FrozenConfigException::class);
        $this->expectExceptionMessageMatches('/sealed/');
        $config->override('key', 'new');
    }

    #[Group('dual-layer')]
    public function testLockAfterSomeOverridesPreservesExisting(): void
    {
        $config = new Config(['a' => 1]);
        $config->override('a', 99);  // dual-layer activated
        $config->lock();              // sealed now

        // Existing override is still visible
        $this->assertSame(99, $config->get('a'));

        // But no more overrides
        $this->expectException(FrozenConfigException::class);
        $config->override('a', 999);
    }

    #[Group('dual-layer')]
    public function testLockDoesNotBlockGet(): void
    {
        $config = new Config(['k' => 'v']);
        $config->lock();

        // Reading is always allowed
        $this->assertSame('v', $config->get('k'));
    }

    #[Group('dual-layer')]
    public function testLockDoesNotBlockSnapshot(): void
    {
        $config = new Config(['k' => 'v']);
        $config->lock();

        $snap = $config->snapshot();
        $this->assertSame('v', $snap->get('k'));
    }

    // =========================================================================
    // Config — lockOverrides() : Lock 2 (override layer sealed after some applied)
    // =========================================================================

    #[Group('dual-layer')]
    public function testLockOverridesSetsFlag(): void
    {
        $config = new Config(['x' => 1]);
        $this->assertFalse($config->areOverridesLocked());
        $config->lockOverrides();
        $this->assertTrue($config->areOverridesLocked());
    }

    #[Group('dual-layer')]
    public function testLockOverridesBlocksFurtherOverrides(): void
    {
        $config = new Config(['feature' => false]);
        $config->override('feature', true);
        $config->lockOverrides();

        $this->expectException(FrozenConfigException::class);
        $this->expectExceptionMessageMatches('/override layer is sealed/');
        $config->override('feature', false);
    }

    #[Group('dual-layer')]
    public function testLockOverridesPreservesAppliedOverrides(): void
    {
        $config = new Config(['mode' => 'prod']);
        $config->override('mode', 'debug');
        $config->lockOverrides();

        $this->assertSame('debug', $config->get('mode'));
    }

    #[Group('dual-layer')]
    public function testLockOverridesBeforeAnyOverrideActsLikeLock(): void
    {
        $config = new Config(['x' => 1]);
        $config->lockOverrides(); // no overrides applied yet

        $this->expectException(FrozenConfigException::class);
        $config->override('x', 2);
    }

    // =========================================================================
    // Config — snapshot()
    // =========================================================================

    #[Group('dual-layer')]
    public function testSnapshotReturnsNewInstance(): void
    {
        $config = new Config(['a' => 1]);
        $this->assertNotSame($config, $config->snapshot());
    }

    #[Group('dual-layer')]
    public function testSnapshotWithNoDualLayerClonesBase(): void
    {
        $config = new Config(['k' => 'v']);
        $snap   = $config->snapshot();

        $this->assertSame('v', $snap->get('k'));
        $this->assertFalse($snap->isDualLayerActive());
    }

    #[Group('dual-layer')]
    public function testSnapshotMergesOverridesIntoBase(): void
    {
        $config = new Config(['db' => ['host' => 'localhost', 'port' => 5432]]);
        $config->override('db.host', 'db.internal');

        $snap = $config->snapshot();

        $this->assertSame('db.internal', $snap->get('db.host'));
        $this->assertSame(5432,          $snap->get('db.port'));
        // Snapshot starts fresh — dual-layer dormant
        $this->assertFalse($snap->isDualLayerActive());
    }

    #[Group('dual-layer')]
    public function testSnapshotIsIsolatedFromOriginal(): void
    {
        $config = new Config(['counter' => 0]);
        $snap   = $config->snapshot();

        $config->override('counter', 99);

        $this->assertSame(0, $snap->get('counter'));
    }

    #[Group('dual-layer')]
    public function testSnapshotOfLockedConfigIsUnlocked(): void
    {
        $config = new Config(['k' => 'v']);
        $config->lock();

        $snap = $config->snapshot();

        // Fresh snapshot — not locked, overrides allowed
        $this->assertFalse($snap->isLocked());
        $snap->override('k', 'mutated');
        $this->assertSame('mutated', $snap->get('k'));
    }

    #[Group('dual-layer')]
    public function testSnapshotAfterLockOverridesIsUnlocked(): void
    {
        $config = new Config(['a' => 1]);
        $config->override('a', 2);
        $config->lockOverrides();

        $snap = $config->snapshot();

        $this->assertFalse($snap->areOverridesLocked());
        $snap->override('a', 3); // must not throw
        $this->assertSame(3, $snap->get('a'));
    }

    // =========================================================================
    // CompiledPhpCache — failure paths
    // =========================================================================

    #[Group('cache')]
    public function testConstructorThrowsOnNonCreatableDirectory(): void
    {
        if (get_current_user() === 'root') {
            $this->markTestSkipped('Cannot test permission errors as root');
        }

        // Point to a path whose parent is read-only so mkdir() will fail
        $readonlyParent = __DIR__ . '/../../.cache_readonly_parent';
        mkdir($readonlyParent, 0555, true);

        try {
            $this->expectException(\RuntimeException::class);
            $this->expectExceptionMessageMatches('/Directory does not exist/');

            new CompiledPhpCache($readonlyParent . '/cannot_create_me');
        } finally {
            chmod($readonlyParent, 0775);
            rmdir($readonlyParent);
        }
    }

    #[Group('cache')]
    public function testSetReturnsFalseWhenDirectoryIsUnwritable(): void
    {
        if (get_current_user() === 'root') {
            $this->markTestSkipped('Cannot test permission errors as root');
        }

        // Build cache in a writable dir, then revoke write permission
        $dir = __DIR__ . '/../../.cache_unwritable';
        mkdir($dir, 0775, true);
        $cache = new CompiledPhpCache($dir);

        chmod($dir, 0555); // read + execute only — file_put_contents will fail

        try {
            $result = $cache->set('key', 'value');
            $this->assertFalse($result);
        } finally {
            chmod($dir, 0775);
            // Clean up any temp files that may have been created
            foreach (glob($dir . '/*') ?: [] as $f) {
                @unlink($f);
            }
            rmdir($dir);
        }
    }

    #[Group('cache')]
    public function testSetMultipleReturnsFalseWhenOneWriteFails(): void
    {
        if (get_current_user() === 'root') {
            $this->markTestSkipped('Cannot test permission errors as root');
        }

        $dir = __DIR__ . '/../../.cache_setmulti';
        mkdir($dir, 0775, true);
        $cache = new CompiledPhpCache($dir);

        // Write the first key successfully, then revoke write permission
        $cache->set('ok_key', 'written');
        chmod($dir, 0555);

        try {
            // 'ok_key' already exists and will also fail (rename target unwritable),
            // 'fail_key' has no file — file_put_contents into $dir fails
            $result = $cache->setMultiple(['ok_key' => 'updated', 'fail_key' => 'never']);
            $this->assertFalse($result);
        } finally {
            chmod($dir, 0775);
            foreach (glob($dir . '/*') ?: [] as $f) {
                @unlink($f);
            }
            rmdir($dir);
        }
    }

    #[Group('cache')]
    public function testDeleteMultipleReturnsFalseWhenOneUnlinkFails(): void
    {
        if (get_current_user() === 'root') {
            $this->markTestSkipped('Cannot test permission errors as root');
        }

        $dir = __DIR__ . '/../../.cache_delmulti';
        mkdir($dir, 0775, true);
        $cache = new CompiledPhpCache($dir);

        // Write two keys
        $cache->set('alpha', 'a');
        $cache->set('beta', 'b');

        // Revoke write permission on the directory — unlink() needs it
        chmod($dir, 0555);

        try {
            $result = $cache->deleteMultiple(['alpha', 'beta']);
            $this->assertFalse($result);
        } finally {
            chmod($dir, 0775);
            foreach (glob($dir . '/*') ?: [] as $f) {
                @unlink($f);
            }
            rmdir($dir);
        }
    }
}
