<?php

declare(strict_types=1);

namespace MonkeysLegion\Mlc\Cache;

use MonkeysLegion\Mlc\Contracts\CacheInterface;

/**
 * High-performance PSR-16 cache powered by PHP OPcache.
 *
 * This driver "compiles" data into valid PHP files using var_export().
 * When get() is called it uses require, allowing OPcache to store the
 * resulting opcode array in shared memory — effectively zero-overhead reads.
 *
 * Design contract:
 *  - TTL is deliberately ignored. This cache is immutable after compilation.
 *  - Eviction is managed explicitly (delete / clear) or by re-compiling.
 *  - Phase 6 runtime overrides live in Config, not here.
 */
final class CompiledPhpCache implements CacheInterface
{
    private string $dir;

    public function __construct(string $cacheDir)
    {
        $this->dir = rtrim($cacheDir, DIRECTORY_SEPARATOR);
        if (!is_dir($this->dir) && !@mkdir($this->dir, 0775, true)) {
            throw new \RuntimeException("Directory does not exist: {$this->dir}");
        }
    }

    private function filePath(string $key): string
    {
        // We use .php so OPcache recognizes and compiles the file
        $safe = preg_replace('/[^A-Za-z0-9_\.\-]/', '_', $key);
        return $this->dir . DIRECTORY_SEPARATOR . $safe . '.generated.php';
    }

    public function get($key, $default = null): mixed
    {
        $path = $this->filePath($key);

        if (!is_file($path)) {
            return $default;
        }

        return require $path;
    }

    public function set($key, $value, $ttl = null): bool
    {
        $path = $this->filePath($key);
        // Note: TTL is deliberately ignored. This is an immutable compiled cache,
        // so it does not support dynamic background expiration.
        // Expiration is managed manually or through cache clearing.

        // Invalidate any existing OPcache entry BEFORE we write the new file,
        // so a concurrent reader cannot get a stale bytecode-cached version.
        if (is_file($path) && function_exists('opcache_invalidate')) {
            opcache_invalidate($path, true);
        }

        // var_export produces valid PHP literals — arrays, scalars, nested structures.
        $content = sprintf(
            "<?php\n\n// Generated by MonkeysLegion CompiledPhpCache — %s\nreturn %s;\n",
            date('Y-m-d H:i:s T'),
            var_export($value, true)
        );

        // Atomic write to prevent reading a half-written file during high traffic
        $tmp = $path . uniqid('', true) . '.tmp';
        if (@file_put_contents($tmp, $content, LOCK_EX) === false) {
            return false;
        }

        return rename($tmp, $path);
    }

    public function delete($key): bool
    {
        $path = $this->filePath($key);
        if (is_file($path)) {
            // In some setups, you might need opcache_invalidate($path) here 
            // to ensure the next 'require' doesn't pull the old version from RAM.
            if (function_exists('opcache_invalidate')) {
                opcache_invalidate($path, true);
            }
            return @unlink($path);
        }
        return true;
    }

    public function has($key): bool
    {
        // Use is_file() — avoids an extra require just to check existence.
        return is_file($this->filePath($key));
    }

    public function clear(): bool
    {
        $files = glob($this->dir . DIRECTORY_SEPARATOR . '*.generated.php');
        foreach ($files ?: [] as $file) {
            if (function_exists('opcache_invalidate')) {
                opcache_invalidate($file, true);
            }
            unlink($file);
        }
        return true;
    }

    public function getMultiple($keys, $default = null): iterable
    {
        $result = [];
        foreach ($keys as $key) {
            $result[$key] = $this->get($key, $default);
        }
        return $result;
    }

    /**
     * @param iterable<string, mixed> $values
     */
    public function setMultiple(iterable $values, null|int|\DateInterval $ttl = null): bool
    {
        $success = true;
        foreach ($values as $key => $value) {
            if (!$this->set($key, $value, $ttl)) {
                $success = false;
            }
        }
        return $success;
    }
    
    /**
     * @param iterable<string> $keys
     */
    public function deleteMultiple(iterable $keys): bool
    {
        $success = true;
        foreach ($keys as $key) {
            if (!$this->delete($key)) {
                $success = false;
            }
        }
        return $success;
    }
}