<?php

declare(strict_types=1);

namespace MonkeysLegion\Mlc\Cache;

use MonkeysLegion\Cache\CacheStats;
use MonkeysLegion\Cache\Lock\ArrayLock;
use MonkeysLegion\Cache\Lock\LockInterface;
use MonkeysLegion\Cache\TaggedCache;
use MonkeysLegion\Mlc\Contracts\CacheInterface;

/**
 * High-performance PSR-16 cache powered by PHP OPcache.
 *
 * This driver "compiles" data into valid PHP files using var_export().
 * When get() is called it uses require, allowing OPcache to store the
 * resulting opcode array in shared memory — effectively zero-overhead reads.
 *
 * Implements MonkeysLegion Cache 2.0 CacheStoreInterface including:
 *  - remember() / rememberForever() for cached computation
 *  - forever() for permanent storage
 *  - pull() for retrieve-and-delete
 *  - add() for store-if-absent
 *  - increment/decrement for counters
 *  - flexible() for stampede protection
 *  - tags() (delegates to TaggedCache)
 *  - lock() (delegates to ArrayLock)
 *  - Typed getters: integer(), boolean(), float(), string(), array()
 *
 * Design contract:
 *  - TTL is deliberately ignored. This cache is immutable after compilation.
 *  - Eviction is managed explicitly (delete / clear) or by re-compiling.
 */
final class CompiledPhpCache implements CacheInterface
{
    private string $dir;

    /** @var int Internal hit counter */
    private int $statHits = 0;

    /** @var int Internal miss counter */
    private int $statMisses = 0;

    /** @var int Internal write counter */
    private int $statWrites = 0;

    /** @var int Internal delete counter */
    private int $statDeletes = 0;

    public function __construct(string $cacheDir)
    {
        $this->dir = rtrim($cacheDir, DIRECTORY_SEPARATOR);
        if (!is_dir($this->dir) && !@mkdir($this->dir, 0775, true)) {
            throw new \RuntimeException("Directory does not exist: {$this->dir}");
        }
    }

    private function filePath(string $key): string
    {
        $safe = preg_replace('/[^A-Za-z0-9_\.\-]/', '_', $key);
        return $this->dir . DIRECTORY_SEPARATOR . $safe . '.generated.php';
    }

    // ── PSR-16 Core ──────────────────────────────────────────────

    public function get(string $key, mixed $default = null): mixed
    {
        $path = $this->filePath($key);

        if (!is_file($path)) {
            $this->statMisses++;
            return $default;
        }

        $this->statHits++;
        return require $path;
    }

    public function set(string $key, mixed $value, \DateInterval|int|null $ttl = null): bool
    {
        $path = $this->filePath($key);

        if (is_file($path) && function_exists('opcache_invalidate')) {
            opcache_invalidate($path, true);
        }

        $content = sprintf(
            "<?php\n\n// Generated by MonkeysLegion CompiledPhpCache — %s\nreturn %s;\n",
            date('Y-m-d H:i:s T'),
            var_export($value, true)
        );

        $tmp = $path . uniqid('', true) . '.tmp';
        if (@file_put_contents($tmp, $content, LOCK_EX) === false) {
            return false;
        }

        $this->statWrites++;
        return rename($tmp, $path);
    }

    public function delete(string $key): bool
    {
        $path = $this->filePath($key);
        if (is_file($path)) {
            if (function_exists('opcache_invalidate')) {
                opcache_invalidate($path, true);
            }
            $this->statDeletes++;
            return @unlink($path);
        }
        return true;
    }

    public function has(string $key): bool
    {
        return is_file($this->filePath($key));
    }

    public function clear(): bool
    {
        $files = glob($this->dir . DIRECTORY_SEPARATOR . '*.generated.php');
        foreach ($files ?: [] as $file) {
            if (function_exists('opcache_invalidate')) {
                opcache_invalidate($file, true);
            }
            unlink($file);
        }
        return true;
    }

    public function getMultiple(iterable $keys, mixed $default = null): iterable
    {
        $result = [];
        foreach ($keys as $key) {
            $result[$key] = $this->get($key, $default);
        }
        return $result;
    }

    public function setMultiple(iterable $values, \DateInterval|int|null $ttl = null): bool
    {
        $success = true;
        foreach ($values as $key => $value) {
            if (!$this->set($key, $value, $ttl)) {
                $success = false;
            }
        }
        return $success;
    }

    public function deleteMultiple(iterable $keys): bool
    {
        $success = true;
        foreach ($keys as $key) {
            if (!$this->delete($key)) {
                $success = false;
            }
        }
        return $success;
    }

    // ── ML Cache 2.0 — remember / forever ───────────────────────

    public function remember(string $key, \DateInterval|int|null $ttl, \Closure $callback): mixed
    {
        if ($this->has($key)) {
            return $this->get($key);
        }

        $value = $callback();
        $this->set($key, $value, $ttl);

        return $value;
    }

    public function rememberForever(string $key, \Closure $callback): mixed
    {
        return $this->remember($key, null, $callback);
    }

    public function forever(string $key, mixed $value): bool
    {
        return $this->set($key, $value);
    }

    public function pull(string $key, mixed $default = null): mixed
    {
        $value = $this->get($key, $default);
        $this->delete($key);

        return $value;
    }

    public function add(string $key, mixed $value, \DateInterval|int|null $ttl = null): bool
    {
        if ($this->has($key)) {
            return false;
        }

        return $this->set($key, $value, $ttl);
    }

    public function touch(string $key, \DateInterval|int $ttl): bool
    {
        // TTL is ignored for compiled cache — touch is a no-op if key exists
        return $this->has($key);
    }

    // ── Atomic counters ─────────────────────────────────────────

    public function increment(string $key, int $value = 1): int|false
    {
        $current = (int) $this->get($key, 0);
        $new = $current + $value;
        $this->set($key, $new);

        return $new;
    }

    public function decrement(string $key, int $value = 1): int|false
    {
        return $this->increment($key, -$value);
    }

    // ── Typed getters ───────────────────────────────────────────

    public function integer(string $key, int $default = 0): int
    {
        $value = $this->get($key);
        return $value !== null ? (int) $value : $default;
    }

    public function boolean(string $key, bool $default = false): bool
    {
        $value = $this->get($key);
        return $value !== null ? (bool) $value : $default;
    }

    public function float(string $key, float $default = 0.0): float
    {
        $value = $this->get($key);
        return $value !== null ? (float) $value : $default;
    }

    public function string(string $key, string $default = ''): string
    {
        $value = $this->get($key);
        return $value !== null ? (string) $value : $default;
    }

    public function array(string $key, array $default = []): array
    {
        $value = $this->get($key);
        return is_array($value) ? $value : $default;
    }

    // ── Stampede protection ──────────────────────────────────────

    public function flexible(string $key, array $ttl, \Closure $callback, float $beta = 1.0): mixed
    {
        // Compiled cache does not support stale-while-revalidate.
        // Fall back to simple remember() with the fresh TTL.
        [, $freshTtl] = $ttl;

        return $this->remember($key, $freshTtl, $callback);
    }

    // ── Tags & Locks ────────────────────────────────────────────

    public function tags(string|array $names): TaggedCache
    {
        return new TaggedCache($this, is_array($names) ? $names : [$names]);
    }

    public function lock(string $name, int $seconds = 0, ?string $owner = null): LockInterface
    {
        return new ArrayLock($name, $seconds, $owner);
    }

    // ── Observability ───────────────────────────────────────────

    public function getPrefix(): string
    {
        return '';
    }

    public function getStats(): CacheStats
    {
        return new CacheStats(
            hits:    $this->statHits,
            misses:  $this->statMisses,
            writes:  $this->statWrites,
            deletes: $this->statDeletes,
        );
    }
}